server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:OtusExamplesDB;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

message-system:
  frontend-service-client-name: frontendService
  database-service-client-name: databaseService
